theme: jekyll-theme-leap-day

title: [Everything except technical details]
description: [Eric thoughts on career (product, entrepreneurship, management), leadership (impact, communication) and hobbies]
